version: "3.8"
services:
    frontend:
        container_name: frontend
        build: ./frontend
        tty: true
        ports:
            - "3000:3000"
        depends_on:
            - backend
        volumes:
            - type: bind
              source: ./frontend
              target: /src/app
            - type: volume
              source: node_modules
              target: /src/app/node_modules
        command: "npm run dev"
        networks:
            - frontend_network
    backend:
        container_name: backend
        build: ./backend
        tty: true
        ports:
            - "8080:8080"
        depends_on:
            - db
        volumes:
            - type: bind
              source: ./backend/app
              target: /go/src/app
        networks:
            - frontend_network
            - backend_network
        environment:
            - GO_ENV=dev

    db:
        container_name: db
        build: ./db
        image: mysql:8.0 # イメージの指定
        tty: true
        platform: linux/x86_64
        ports:
            - 3306:3306
        env_file:
            - ./db/.env
        volumes:
            - mysql_go_next_todo_volume:/var/lib/mysql
            - ./db/sql/init.sql:/docker-entrypoint-initdb.d/init.sql # 初期化スクリプトのマウント
        networks:
            - backend_network

volumes:
    mysql_go_next_todo_volume:
    node_modules:


networks:
    frontend_network:
        external: true
    backend_network:
        external: true
